---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  namespace: w255
  labels:
    app: project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-deployment
  template:
    metadata:
      labels:
        app: project-deployment
    spec:
      containers:
        - name: project-prediction-container
          image: project:latest
          env:
            - name: REDIS_URL
              value: redis://redis-service
            - name: REDIS_PORT
              value: '6379'
          resources:
            requests:
              cpu: 200m
              memory: 700Mi
            limits:
              cpu: 1500m
              memory: 2Gi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
      initContainers:
        - name: init-verify-redis-service-dns
          image: busybox
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 500Mi
          command:
            [
              "sh",
              "-c",
              "until nc -vz redis-service 6379; do echo 'waiting for redis service from DNS'; sleep 2; done",
            ]
        - name: init-verify-redis-ready
          image: busybox
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 500Mi
          command:
            [
              "sh",
              "-c",
              "until (printf 'PING\r\n';) | nc redis-service 6379; do echo 'waiting for redis to PONG'; sleep 1; done",
              e,
            ]
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-deployment #Changed to name of container that is being scaled
  minReplicas: 1
  maxReplicas: 40
  targetCPUUtilizationPercentage: 20 #Change target utilization percentage to speed up scaling
